service: serverless-hello-world

provider:
  name: aws
  runtime: nodejs8.10

functions:
  ping:
    handler: lambdas/ping.handler
    events:
      - http:
          path: ping
          method: get
          cors: true

  pingServices:
    handler: lambdas/pingServices.handler
    events:
      - schedule: rate(1 minute)

  addEndpoint:
    handler: lambdas/addEndpoint.handler
    events:
      - http:
          path: addEndpoint
          method: post
          cors: true

  getEndpoints:
    handler: lambdas/getEndpoints.handler
    events:
      - http:
          path: getEndpoints
          method: get
          cors: true

  deleteEndpoint:
    handler: lambdas/deleteEndpoint.handler
    events:
      - http:
          path: deleteEndpoint
          method: delete
          cors: true

plugins:
  - serverless-offline
