service: serverless-hello-world

provider:
  name: aws
  runtime: nodejs8.10

functions:
  ping:
    handler: handler.ping
    events:
      - http:
          path: ping
          method: get
          cors: true
plugins:
  - serverless-offline