service: ping

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-central-1

  pingServices:
    handler: lambdas/pingServices.handler
    events:
      - schedule: rate(1 minute)

  getPings:
    handler: lambdas/getPings.handler
    events:
      - http:
          path: getPings
          method: get
          cors: true

  addEndpoint:
    handler: lambdas/addEndpoint.handler
    events:
      - http:
          path: addEndpoint
          method: post
          cors: true

  getEndpoints:
    handler: lambdas/getEndpoints.handler
    events:
      - http:
          path: getEndpoints
          method: get
          cors: true

  deleteEndpoint:
    handler: lambdas/deleteEndpoint.handler
    events:
      - http:
          path: deleteEndpoint
          method: delete
          cors: true

plugins:
  - serverless-offline
